In [8]:
import numpy as np
import pandas as pd

In [94]:
movies=pd.read_csv(r'E:\Projects\Movie Recommender\tmdb_5000_movies.csv')
credits=pd.read_csv(r'E:\Projects\Movie Recommender\tmdb_5000_credits.csv')

In [96]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [98]:
movies.shape

(4803, 20)

In [100]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [102]:
credits.shape

(4803, 4)

In [104]:
movies=movies.merge(credits,on='title')

In [108]:
movies.shape

(4809, 23)

In [110]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [112]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [114]:
movies.shape

(4809, 7)

In [116]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [120]:
movies.dropna(inplace=True)

In [122]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [124]:
movies.shape

(4806, 7)

In [128]:
movies.duplicated().sum()

0

In [132]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [138]:
import ast

In [144]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [148]:
movies['genres']=movies['genres'].apply(convert)

In [150]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [152]:
movies['keywords']=movies['keywords'].apply(convert)

In [154]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [156]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
            
    return L

In [162]:
movies['cast']=movies['cast'].apply(convert3)

In [163]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [172]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [176]:
movies['crew']=movies['crew'].apply(fetch_director)

In [177]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]

In [182]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [184]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]

In [188]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ",'') for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ",'') for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ",'') for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ",'') for i in x])

In [190]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]

In [192]:
 movies.shape

(4806, 7)

In [608]:
movies['tags']=movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [610]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."

In [612]:
new_df=movies[['movie_id','title','tags']]

In [614]:
new_df.head(3)

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."

In [616]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Vignesh Bodiga\AppData\Local\Temp\ipykernel_17256\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [618]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Vignesh Bodiga\AppData\Local\Temp\ipykernel_17256\1172989878.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [619]:
new_df.head(3)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...

In [620]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [626]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [632]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoÃ«kravitz'],
      dtype=object)

In [634]:
from sklearn.metrics.pairwise import cosine_similarity

In [636]:
similarity=cosine_similarity(vectors)

In [637]:
similarity[0]

array([1.        , 0.06818182, 0.07644708, ..., 0.04307305, 0.        ,
       0.        ])

In [644]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:]

[(1214, 0.27028123880866767),
 (582, 0.23162743094465488),
 (2329, 0.22996655275195),
 (3728, 0.22498852128662872),
 (507, 0.22438727760202976),
 (539, 0.22305671869347438),
 (1916, 0.22010219462003333),
 (2405, 0.2175970699446223),
 (4046, 0.20751433915982237),
 (2782, 0.20695933859617893),
 (322, 0.20691022044226628),
 (577, 0.20100756305184242),
 (778, 0.19968076595771794),
 (1202, 0.19790977371009408),
 (61, 0.19596237883454903),
 (2969, 0.19462473604038075),
 (74, 0.1938287215142766),
 (151, 0.1928473039599675),
 (4190, 0.1928473039599675),
 (3606, 0.19145989526687088),
 (1087, 0.18540496217739155),
 (3997, 0.18463723646899916),
 (1440, 0.18281810603178267),
 (260, 0.1809806914982567),
 (973, 0.1809806914982567),
 (1192, 0.17837651700316892),
 (3325, 0.1776672636296754),
 (3671, 0.175919798853417),
 (1533, 0.17588161767036212),
 (495, 0.17407765595569785),
 (4405, 0.17407765595569785),
 (972, 0.17348855898381338),
 (4, 0.17056057308448835),
 (3536, 0.16898159235484367),
 (83, 0.16888013236829963),
 (2997, 0.16854996561581054),
 (27, 0.1682904582015223),
 (305, 0.1682904582015223),
 (184, 0.16685595311797868),
 (47, 0.16351748504193214),
 (942, 0.16262312563634837),
 (2200, 0.160930171455096),
 (172, 0.1599005372667078),
 (2071, 0.1599005372667078),
 (4336, 0.15909090909090912),
 (1273, 0.15745916432444343),
 (1327, 0.15745916432444343),
 (168, 0.15731330124142318),
 (3160, 0.15701373439577193),
 (595, 0.15559397856603546),
 (1069, 0.15392982399673985),
 (1319, 0.15386436372416595),
 (220, 0.15075567228888181),
 (529, 0.15075567228888181),
 (661, 0.15075567228888181),
 (36, 0.1492405014489273),
 (300, 0.1492405014489273),
 (931, 0.1487044791289829),
 (1199, 0.1487044791289829),
 (373, 0.14782809899727067),
 (2727, 0.14782809899727067),
 (41, 0.14777011582226215),
 (150, 0.14716573653773893),
 (1176, 0.14673479641335554),
 (1827, 0.1463423517512409),
 (4008, 0.14625448482542613),
 (139, 0.14519080172812554),
 (2511, 0.14506471329641488),
 (91, 0.14484136487558028),
 (1342, 0.14484136487558028),
 (342, 0.1446354779699756),
 (581, 0.14245072057454744),
 (1669, 0.1421338109037403),
 (1978, 0.14126448280440335),
 (158, 0.1411569346481171),
 (56, 0.1399731277389636),
 (1475, 0.13977653617040256),
 (3352, 0.13762047064079508),
 (838, 0.1374416265488099),
 (2756, 0.13623731522826651),
 (208, 0.13483997249264842),
 (1271, 0.13483997249264842),
 (1379, 0.13483997249264842),
 (1392, 0.13402192668680965),
 (127, 0.1340050420345616),
 (94, 0.13336626734231613),
 (187, 0.13336626734231613),
 (1934, 0.13336626734231613),
 (937, 0.1332504477222565),
 (1325, 0.1315903389919538),
 (1484, 0.1315903389919538),
 (2968, 0.1315903389919538),
 (557, 0.1305582419667734),
 (1353, 0.1305582419667734),
 (149, 0.13005121775247103),
 (461, 0.1292719224987548),
 (3407, 0.1292719224987548),
 (1054, 0.12921914767618442),
 (4538, 0.12921914767618442),
 (311, 0.1292191476761844),
 (1961, 0.12892415701965754),
 (3779, 0.128564869306645),
 (67, 0.12792042981336627),
 (513, 0.12792042981336627),
 (413, 0.12741179785940637),
 (568, 0.12741179785940637),
 (46, 0.1266600992762247),
 (157, 0.1257389226923863),
 (490, 0.1257389226923863),
 (1299, 0.1257389226923863),
 (1941, 0.1256297269074015),
 (108, 0.12543630150106364),
 (17, 0.12436708454077278),
 (502, 0.12424730498438732),
 (275, 0.12392039927415242),
 (859, 0.12392039927415242),
 (2165, 0.12392039927415242),
 (2492, 0.12392039927415242),
 (4077, 0.12392039927415242),
 (1320, 0.12351231781710247),
 (2580, 0.12309149097933275),
 (3980, 0.12309149097933275),
 (579, 0.12227899701112964),
 (294, 0.12227899701112963),
 (1804, 0.12227899701112963),
 (1295, 0.12196734422726127),
 (2129, 0.12196734422726127),
 (95, 0.12196734422726126),
 (777, 0.12087344460380703),
 (31, 0.1207011373963169),
 (1556, 0.1207011373963169),
 (2177, 0.1207011373963169),
 (668, 0.12060453783110546),
 (1369, 0.12060453783110546),
 (26, 0.11980845957463077),
 (843, 0.11918282365569904),
 (2682, 0.11918282365569904),
 (3626, 0.11918282365569904),
 (505, 0.11826247919781653),
 (2374, 0.11826247919781653),
 (111, 0.11776030079682895),
 (589, 0.11776030079682895),
 (2869, 0.11776030079682895),
 (3620, 0.11772040233700279),
 (206, 0.11725441178024137),
 (4228, 0.11631052629980887),
 (1297, 0.11631052629980886),
 (2648, 0.1160517706371319),
 (122, 0.11495012246792571),
 (1084, 0.11495012246792571),
 (1218, 0.11487593716012254),
 (466, 0.11396057645963795),
 (476, 0.11396057645963795),
 (773, 0.11396057645963795),
 (935, 0.11396057645963795),
 (7, 0.11306675421666137),
 (84, 0.11306675421666137),
 (102, 0.11306675421666137),
 (1737, 0.11306675421666137),
 (1874, 0.11306675421666137),
 (1711, 0.11306675421666136),
 (4348, 0.11306675421666136),
 (138, 0.11236664374387369),
 (1013, 0.11236664374387369),
 (2446, 0.11236664374387369),
 (3233, 0.11236664374387369),
 (487, 0.11197850219117086),
 (1770, 0.11197850219117086),
 (4673, 0.11197850219117086),
 (72, 0.11113855611859677),
 (1397, 0.11113855611859677),
 (2368, 0.11113855611859677),
 (1002, 0.11009637651263605),
 (1045, 0.11009637651263605),
 (1654, 0.11009637651263605),
 (549, 0.10994987428338562),
 (2476, 0.1096908636190696),
 (3998, 0.1096908636190696),
 (654, 0.10889310129609417),
 (454, 0.10879853497231115),
 (3374, 0.10830607221477648),
 (160, 0.10770505460691618),
 (14, 0.107682623063487),
 (126, 0.107682623063487),
 (166, 0.107682623063487),
 (438, 0.107682623063487),
 (3210, 0.10726454129012915),
 (900, 0.10660035817780522),
 (1613, 0.10660035817780522),
 (2785, 0.10660035817780522),
 (134, 0.10660035817780521),
 (167, 0.10660035817780521),
 (249, 0.10660035817780521),
 (786, 0.10660035817780521),
 (1272, 0.10660035817780521),
 (2144, 0.10660035817780521),
 (1000, 0.10586770098608783),
 (368, 0.10497277621629561),
 (678, 0.10497277621629561),
 (1094, 0.10497277621629561),
 (1829, 0.10497277621629561),
 (4468, 0.10497277621629561),
 (536, 0.10453025125088636),
 (3145, 0.1044465935734187),
 (1493, 0.10444659357341869),
 (2327, 0.1037571695799112),
 (228, 0.10353942082032278),
 (432, 0.10353942082032278),
 (740, 0.10353942082032278),
 (1508, 0.10353942082032278),
 (2280, 0.10353942082032278),
 (3628, 0.10353942082032278),
 (50, 0.10341753799900383),
 (1029, 0.10341753799900383),
 (2813, 0.10341753799900383),
 (467, 0.10257624248277727),
 (870, 0.10257624248277727),
 (87, 0.1019294382875251),
 (422, 0.1019294382875251),
 (483, 0.1019294382875251),
 (238, 0.10176802973291377),
 (420, 0.10163945352271772),
 (85, 0.10154529930749041),
 (2630, 0.10112997936948631),
 (2670, 0.10112997936948631),
 (3719, 0.10112997936948631),
 (43, 0.10072787050317253),
 (123, 0.10072787050317253),
 (2543, 0.10072787050317253),
 (3091, 0.10072787050317253),
 (232, 0.10050378152592121),
 (332, 0.10050378152592121),
 (544, 0.10050378152592121),
 (781, 0.10050378152592121),
 (2056, 0.10050378152592121),
 (2861, 0.10050378152592121),
 (3496, 0.10050378152592121),
 (4095, 0.10050378152592121),
 (4777, 0.10050378152592121),
 (81, 0.09988907373180403),
 (229, 0.09988907373180403),
 (3307, 0.09984038297885897),
 (1570, 0.09928550884822428),
 (889, 0.09927330486454494),
 (148, 0.09913631941932194),
 (236, 0.09913631941932194),
 (2737, 0.09913631941932194),
 (3405, 0.09913631941932194),
 (3426, 0.09913631941932194),
 (3924, 0.09913631941932194),
 (995, 0.09897594780811197),
 (1414, 0.09897594780811197),
 (307, 0.09883693657685838),
 (627, 0.09869275424396534),
 (1346, 0.09869275424396534),
 (2517, 0.09869275424396534),
 (3081, 0.09869275424396534),
 (4201, 0.09869275424396534),
 (199, 0.09813358399735746),
 (270, 0.09813358399735746),
 (2095, 0.09813358399735746),
 (2435, 0.09813358399735746),
 (939, 0.09811049102515929),
 (1612, 0.0978231976089037),
 (2171, 0.0978231976089037),
 (2243, 0.0978231976089037),
 (4017, 0.0978231976089037),
 (2102, 0.09731236802019037),
 (754, 0.09656090991705352),
 (814, 0.09656090991705352),
 (1035, 0.09656090991705352),
 (1235, 0.09656090991705352),
 (2068, 0.09656090991705352),
 (182, 0.09651142956027287),
 (572, 0.09651142956027287),
 (1451, 0.09651142956027287),
 (808, 0.09642365197998373),
 (1154, 0.09642365197998373),
 (1520, 0.09642365197998373),
 (3619, 0.09642365197998373),
 (3659, 0.09642365197998373),
 (4196, 0.09642365197998373),
 (52, 0.09572994763343545),
 (75, 0.09534625892455924),
 (223, 0.09534625892455924),
 (1288, 0.09534625892455924),
 (262, 0.09496714704969828),
 (425, 0.09496714704969828),
 (653, 0.09430419201928972),
 (1497, 0.09430419201928972),
 (2758, 0.09430419201928972),
 (3837, 0.09430419201928972),
 (170, 0.09422229518055114),
 (692, 0.09422229518055114),
 (1401, 0.09422229518055114),
 (1492, 0.09422229518055114),
 (2494, 0.09422229518055114),
 (687, 0.09417632186960223),
 (787, 0.09417632186960223),
 (1610, 0.09417632186960223),
 (3338, 0.09417632186960223),
 (3872, 0.09417632186960223),
 (3439, 0.09349469900084573),
 (28, 0.09304842103984709),
 (203, 0.09304842103984709),
 (449, 0.09304842103984709),
 (1819, 0.09304842103984709),
 (189, 0.09231861823449956),
 (3053, 0.09231861823449956),
 (239, 0.09208868358546966),
 (491, 0.09208868358546966),
 (68, 0.09196009797434057),
 (295, 0.09196009797434057),
 (472, 0.09196009797434057),
 (632, 0.09196009797434057),
 (1095, 0.09196009797434057),
 (1107, 0.09196009797434057),
 (1143, 0.09196009797434057),
 (1156, 0.09196009797434057),
 (1292, 0.09196009797434057),
 (1767, 0.09196009797434057),
 (2249, 0.09196009797434057),
 (2552, 0.09196009797434057),
 (3150, 0.09196009797434057),
 (3618, 0.09196009797434057),
 (3781, 0.09196009797434057),
 (21, 0.09090909090909091),
 (131, 0.09090909090909091),
 (510, 0.09090909090909091),
 (986, 0.09090909090909091),
 (1111, 0.09090909090909091),
 (2783, 0.09045340337332909),
 (4472, 0.09045340337332909),
 (1771, 0.09009374626955591),
 (4545, 0.09009374626955591),
 (10, 0.08989331499509895),
 (480, 0.08989331499509895),
 (2237, 0.08989331499509895),
 (3753, 0.08989331499509895),
 (3933, 0.08989331499509895),
 (5, 0.08945703337056415),
 (213, 0.08945703337056415),
 (312, 0.08891084489487741),
 (535, 0.08891084489487741),
 (643, 0.08891084489487741),
 (1080, 0.08891084489487741),
 (1193, 0.08891084489487741),
 (2588, 0.08891084489487741),
 (2646, 0.08891084489487741),
 (3006, 0.08891084489487741),
 (153, 0.0888336318148377),
 (1571, 0.0886968593983624),
 (2319, 0.0886968593983624),
 (2452, 0.0886968593983624),
 (2641, 0.0886968593983624),
 (3734, 0.0886968593983624),
 (3899, 0.0886968593983624),
 (4016, 0.0886968593983624),
 (4254, 0.0886968593983624),
 (4490, 0.0886968593983624),
 (1435, 0.08822308415507318),
 (266, 0.0879598994267085),
 (371, 0.0879598994267085),
 (3253, 0.0879598994267085),
 (3609, 0.0879598994267085),
 (4178, 0.0879598994267085),
 (18, 0.0876249546540977),
 (363, 0.0876249546540977),
 (121, 0.08703882797784893),
 (193, 0.08703882797784893),
 (410, 0.08703882797784893),
 (660, 0.08703882797784893),
 (1075, 0.08703882797784893),
 (1442, 0.08703882797784893),
 (1682, 0.08703882797784893),
 (1723, 0.08703882797784893),
 (2157, 0.08703882797784893),
 (2816, 0.08703882797784893),
 (3632, 0.08703882797784893),
 (4133, 0.08703882797784893),
 (4203, 0.08703882797784893),
 (4331, 0.08703882797784893),
 (4403, 0.08703882797784893),
 (230, 0.08646430798325933),
 (1688, 0.0861460984507896),
 (2523, 0.0861460984507896),
 (3138, 0.0861460984507896),
 (4343, 0.0861460984507896),
 (256, 0.08547043234472845),
 (624, 0.08547043234472845),
 (715, 0.08547043234472845),
 (791, 0.08547043234472845),
 (1717, 0.08547043234472845),
 (2049, 0.08547043234472845),
 (2392, 0.08547043234472845),
 (3481, 0.08547043234472845),
 (3535, 0.08547043234472845),
 (3952, 0.08547043234472845),
 (1483, 0.08534859274986485),
 (334, 0.08528028654224418),
 (1842, 0.08528028654224418),
 (3387, 0.08528028654224418),
 (3551, 0.08528028654224418),
 (2566, 0.0848066914440948),
 (11, 0.0844400661841498),
 (419, 0.0844400661841498),
 (445, 0.0844400661841498),
 (898, 0.0844400661841498),
 (1902, 0.0844400661841498),
 (785, 0.08427498280790527),
 (799, 0.08427498280790527),
 (200, 0.08398387664337814),
 (794, 0.08398387664337814),
 (1278, 0.08398387664337814),
 (2089, 0.08398387664337814),
 (2558, 0.08398387664337814),
 (2647, 0.08398387664337814),
 (2864, 0.08398387664337814),
 (2955, 0.08398387664337814),
 (3446, 0.08398387664337814),
 (301, 0.08375315127160099),
 (278, 0.08362420100070908),
 (331, 0.08362420100070908),
 (412, 0.08362420100070908),
 (596, 0.08362420100070908),
 (602, 0.08362420100070908),
 (2484, 0.08362420100070908),
 (2709, 0.08362420100070908),
 (3460, 0.08362420100070908),
 (3718, 0.08362420100070908),
 (3879, 0.08362420100070908),
 (4516, 0.08362420100070908),
 (234, 0.08283153665625823),
 (508, 0.08283153665625823),
 (1697, 0.08283153665625823),
 (2111, 0.0827379240401869),
 (319, 0.08257228238447704),
 (1257, 0.08257228238447704),
 (1304, 0.08257228238447704),
 (1476, 0.08257228238447704),
 (2212, 0.08257228238447704),
 (274, 0.08215419219227854),
 (217, 0.08206099398622183),
 (1173, 0.08206099398622183),
 (2031, 0.08206099398622183),
 (479, 0.08175874252096607),
 (827, 0.08131156281817417),
 (1231, 0.08131156281817417),
 (2350, 0.08131156281817417),
 (209, 0.08122955416108235),
 (233, 0.08122955416108235),
 (244, 0.08122955416108235),
 (356, 0.08122955416108235),
 (1741, 0.08122955416108235),
 (2247, 0.08122955416108235),
 (143, 0.08058229640253803),
 (330, 0.08058229640253803),
 (383, 0.08058229640253803),
 (752, 0.08058229640253803),
 (1274, 0.08058229640253803),
 (1355, 0.08058229640253803),
 (2105, 0.08058229640253803),
 (2788, 0.08058229640253803),
 (2792, 0.08058229640253803),
 (3554, 0.08058229640253803),
 (4353, 0.08058229640253803),
 (4502, 0.08058229640253803),
 (3366, 0.08026441628216505),
 (141, 0.0799502686333539),
 (389, 0.0799502686333539),
 (1470, 0.0799502686333539),
 (1850, 0.0799502686333539),
 (3133, 0.0799502686333539),
 (3674, 0.0799502686333539),
 (4754, 0.0799502686333539),
 (243, 0.07987230638308718),
 (671, 0.07987230638308718),
 (746, 0.07987230638308718),
 (1828, 0.07987230638308718),
 (2359, 0.07987230638308718),
 (2736, 0.07987230638308718),
 (3903, 0.07987230638308718),
 (813, 0.07918075824648958),
 (1028, 0.07918075824648958),
 (1630, 0.07901744265512675),
 (745, 0.0787295821622217),
 (1585, 0.0787295821622217),
 (1752, 0.0787295821622217),
 (2640, 0.0787295821622217),
 (2656, 0.0787295821622217),
 (4560, 0.0787295821622217),
 (103, 0.07850686719788597),
 (1635, 0.07850686719788597),
 (129, 0.0778498944161523),
 (473, 0.0778498944161523),
 (541, 0.0778498944161523),
 (1017, 0.0778498944161523),
 (2966, 0.0778498944161523),
 (3726, 0.0778498944161523),
 (4587, 0.0778498944161523),
 (4654, 0.0778498944161523),
 (4737, 0.0778498944161523),
 (263, 0.07756315349925287),
 (292, 0.07756315349925287),
 (511, 0.07756315349925287),
 (564, 0.07756315349925287),
 (960, 0.07756315349925287),
 (978, 0.07756315349925287),
 (1374, 0.07756315349925287),
 (1582, 0.07756315349925287),
 (1924, 0.07756315349925287),
 (3299, 0.07756315349925287),
 (3320, 0.07756315349925287),
 (4657, 0.07756315349925287),
 (3, 0.07733602811121826),
 (2444, 0.07733602811121826),
 (734, 0.07720914364821829),
 (1009, 0.07720914364821829),
 (45, 0.07658395810674837),
 (2382, 0.07653459686532839),
 (2, 0.07644707871564382),
 (775, 0.07644707871564382),
 (863, 0.07644707871564382),
 (878, 0.07644707871564382),
 (922, 0.07644707871564382),
 (1140, 0.07644707871564382),
 (2163, 0.07644707871564382),
 (2396, 0.07644707871564382),
 (2579, 0.07644707871564382),
 (2657, 0.07644707871564382),
 (4626, 0.07644707871564382),
 (63, 0.07597371763975862),
 (169, 0.07597371763975862),
 (768, 0.07597371763975862),
 (4506, 0.07597371763975862),
 (9, 0.07537783614444091),
 (23, 0.07537783614444091),
 (88, 0.07537783614444091),
 (142, 0.07537783614444091),
 (369, 0.07537783614444091),
 (400, 0.07537783614444091),
 (899, 0.07537783614444091),
 (901, 0.07537783614444091),
 (1137, 0.07537783614444091),
 (1247, 0.07537783614444091),
 (1515, 0.07537783614444091),
 (1569, 0.07537783614444091),
 (1743, 0.07537783614444091),
 (1880, 0.07537783614444091),
 (2270, 0.07537783614444091),
 (2300, 0.07537783614444091),
 (2441, 0.07537783614444091),
 (2667, 0.07537783614444091),
 (2711, 0.07537783614444091),
 (2852, 0.07537783614444091),
 (2876, 0.07537783614444091),
 (3100, 0.07537783614444091),
 (3468, 0.07537783614444091),
 (3525, 0.07537783614444091),
 (3558, 0.07537783614444091),
 (3947, 0.07537783614444091),
 (4279, 0.07537783614444091),
 (4316, 0.07537783614444091),
 (4641, 0.07537783614444091),
 (486, 0.07500375028127344),
 (1779, 0.07479575920067658),
 (125, 0.07460470969529907),
 (12, 0.07435223956449145),
 (306, 0.07435223956449145),
 (315, 0.07435223956449145),
 (349, 0.07435223956449145),
 (920, 0.07435223956449145),
 (1164, 0.07435223956449145),
 (1205, 0.07435223956449145),
 (1938, 0.07435223956449145),
 (3026, 0.07435223956449145),
 (3231, 0.07435223956449145),
 (3295, 0.07435223956449145),
 (3762, 0.07435223956449145),
 (3814, 0.07435223956449145),
 (3849, 0.07435223956449145),
 (190, 0.07422696190252054),
 (222, 0.07422696190252054),
 (19, 0.07367094686837573),
 (48, 0.07367094686837573),
 (612, 0.07367094686837573),
 (618, 0.07367094686837573),
 (1344, 0.07367094686837573),
 (1824, 0.07367094686837573),
 (35, 0.07336739820667779),
 (325, 0.07336739820667779),
 (457, 0.07336739820667779),
 (894, 0.07336739820667779),
 (1025, 0.07336739820667779),
 (1745, 0.07336739820667779),
 (2124, 0.07336739820667779),
 (2291, 0.07336739820667779),
 (164, 0.07336739820667777),
 (1920, 0.07312724241271307),
 (3976, 0.07312724241271307),
 (4492, 0.07312724241271307),
 (51, 0.07259540086406277),
 (501, 0.07259540086406277),
 (1894, 0.07259540086406277),
 (33, 0.07242068243779014),
 (1519, 0.07242068243779014),
 (2679, 0.07242068243779014),
 (3803, 0.07242068243779014),
 (812, 0.07207499701564472),
 (1303, 0.07207499701564472),
 (1530, 0.07207499701564471),
 (32, 0.07156562669645132),
 (1922, 0.07156562669645132),
 (2001, 0.07156562669645132),
 (854, 0.07150969419341943),
 (1030, 0.07150969419341943),
 (1159, 0.07150969419341943),
 (1179, 0.07150969419341943),
 (4266, 0.07150969419341943),
 (4558, 0.07150969419341943),
 (4624, 0.07150969419341943),
 (534, 0.07106690545187015),
 (1526, 0.07106690545187015),
 (2708, 0.07106690545187015),
 (2797, 0.07106690545187015),
 (2857, 0.07106690545187015),
 (3178, 0.07106690545187015),
 (3429, 0.07106690545187015),
 (3830, 0.07106690545187015),
 (4009, 0.07106690545187015),
 (4234, 0.07106690545187015),
 (105, 0.07063224140220167),
 (241, 0.07063224140220167),
 (362, 0.07063224140220167),
 (402, 0.07063224140220167),
 (587, 0.07063224140220167),
 (1078, 0.07063224140220167),
 (2014, 0.07063224140220167),
 (2159, 0.07063224140220167),
 (3162, 0.07063224140220167),
 (403, 0.07057846732405855),
 (607, 0.07057846732405855),
 (2199, 0.07057846732405855),
 (3329, 0.07029019463944167),
 (286, 0.07009996372327816),
 (1655, 0.07009996372327816),
 (4429, 0.07009996372327816),
 (37, 0.06978631577988531),
 (227, 0.06978631577988531),
 (235, 0.06978631577988531),
 (242, 0.06978631577988531),
 (492, 0.06978631577988531),
 (547, 0.06978631577988531),
 (855, 0.06978631577988531),
 (1267, 0.06978631577988531),
 (1291, 0.06978631577988531),
 (2847, 0.06978631577988531),
 (2936, 0.06978631577988531),
 (3283, 0.06978631577988531),
 (38, 0.06963106238227913),
 (246, 0.06963106238227913),
 (1280, 0.06963106238227913),
 (381, 0.06917144638660747),
 (1660, 0.06917144638660747),
 (1766, 0.06917144638660747),
 (2161, 0.06917144638660747),
 (2293, 0.06917144638660747),
 (2873, 0.06917144638660747),
 (3115, 0.06917144638660747),
 (4431, 0.06917144638660747),
 (39, 0.06897007348075543),
 (70, 0.06897007348075543),
 (98, 0.06897007348075543),
 (112, 0.06897007348075543),
 (207, 0.06897007348075543),
 (219, 0.06897007348075543),
 (680, 0.06897007348075543),
 (1363, 0.06897007348075543),
 (2231, 0.06897007348075543),
 (2445, 0.06897007348075543),
 (2848, 0.06897007348075543),
 (2914, 0.06897007348075543),

In [662]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [666]:
recommend('Inception')

Timecop
12 Rounds
Commando
Me You and Five Bucks
Micmacs

In [685]:
import pickle

In [687]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [689]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [691]:
pickle.dump(similarity,open('similarity.pkl','wb'))